### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by odddozen** [RoboticVisionOrg/rv_manipulation_driver#1]
Hi Gavin/Team,

Across this and a few other of your repos (vgs_test, etc) you have referred a few dependencies that rosdep cannot identify - specially rv_msgs, python-numpy-quaternion (should be python-numpy-quaternion-pip?) and python-transforms3d (should be python-transforms3d-pip?).

**Comment by suddrey-qut** [comment]
Hi,
I have corrected the dependencies for python-numpy-quaternion and python-transforms3d. 

You can find rv_msgs here: https://github.com/RoboticVisionOrg/rv_msgs

Hopefully this resolves your issue.
Gavin

**Comment by stevencolinmartin** [comment]
This work has been superseded by ArmEr 
https://github.com/qcr/armer
